name: Builds
on:
  push:
    branches:
      - main
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            target: "apk --debug"
          - os: ubuntu
            target: "appbundle --debug"
          - os: macos
            target: "ios --no-codesign"
          - os: macos
            target: macos
          - os: ubuntu
            target: web
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@v2
        with:
          channel: master
          cache: true
      - run: flutter config --enable-macos-desktop
        if: ${{ matrix.os == 'macos' }}
      - run: flutter doctor -v

      # Checkout code and get packages.
      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get
      - run: flutter build ${{ matrix.target }}
